### ISSUE TITLE
图片不显示

### ISSUE THREAD

**Issue by taixiang** [zzhoujay/Html#3]
跑的这个项目的demo，把里面图片地址换了
`<img src=\"https://www.baidu.com/img/bd_logo1.png\" alt=\"演示\" title=\"演示\" style=\"max-width:100%;\"></a></p>\n" +`

**Comment by 1756211858** [comment]
我也是图片不显示   https://juejin.im/post/5add7571f265da0b9f3fe1f9   爬取这个网站的数据

**Comment by zzhoujay** [comment]
设置了ImageGetter没，显示图片需要设置ImageGetter，或者配合[RichText](https://github.com/zzhoujay/RichText)使用

**Comment by 1756211858** [comment]
`import android.content.Context;
import android.graphics.Bitmap;
import android.graphics.Canvas;
import android.graphics.drawable.BitmapDrawable;
import android.graphics.drawable.Drawable;
import android.graphics.drawable.LevelListDrawable;
import android.support.annotation.NonNull;
import android.support.annotation.Nullable;
import android.text.Html;
import android.util.Log;
import android.widget.TextView;


import com.bumptech.glide.Glide;
import com.bumptech.glide.request.target.SimpleTarget;
import com.bumptech.glide.request.transition.Transition;

public class URLImageParser implements Html.ImageGetter {
    private Context context;
    private TextView textView;
    private URLDrawable bitmapDrawable;
    public URLImageParser(Context context, TextView textView) {
        this.context = context;
        this.textView = textView;


    }

    @Override
    public Drawable getDrawable(String source) {
        bitmapDrawable = new URLDrawable();
        Glide.with(context).asBitmap().load(source).into(new SimpleTarget<Bitmap>() {
            @Override
            public void onResourceReady(@NonNull Bitmap resource, @Nullable Transition<? super Bitmap> transition) {
                bitmapDrawable.bitmap=resource;
                bitmapDrawable.setBounds(0, 0, resource.getWidth(), resource.getHeight());
                textView.invalidate();
                textView.setText(textView.getText());
            }


        });
        return bitmapDrawable;
    }
    public class URLDrawable extends BitmapDrawable {
        public Bitmap bitmap;

        @Override
        public void draw(Canvas canvas) {
            super.draw(canvas);
            if (bitmap != null) {
                canvas.drawBitmap(bitmap, 0, 0, getPaint());
            }
        }
    }
}
`

**Comment by 1756211858** [comment]
` public Drawable getDrawable(String source) {
        bitmapDrawable = new URLDrawable();
        Glide.with(context).asBitmap().load(source).into(new SimpleTarget<Bitmap>() {
            @Override
            public void onResourceReady(@NonNull Bitmap resource, @Nullable Transition<? super Bitmap> transition) {
                bitmapDrawable.bitmap=resource;
                bitmapDrawable.setBounds(0, 0, resource.getWidth(), resource.getHeight());
                textView.invalidate();
                textView.setText(textView.getText());
            }


        });
        return bitmapDrawable;
    }`

**Comment by 1756211858** [comment]
`` public Drawable getDrawable(String source) {
        bitmapDrawable = new URLDrawable();
        Glide.with(context).asBitmap().load(source).into(new SimpleTarget<Bitmap>() {
            @Override
            public void onResourceReady(@NonNull Bitmap resource, @Nullable Transition<? super Bitmap> transition) {
                bitmapDrawable.bitmap=resource;
                bitmapDrawable.setBounds(0, 0, resource.getWidth(), resource.getHeight());
                textView.invalidate();
                textView.setText(textView.getText());
            }


        });
        return bitmapDrawable;
    }
